spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: zoo
      port: 27017
      host: localhost
      auto-index-creation: true

server:
  servlet:
    context-path: /api




